spring:
  application:
    name: wu-ai-pdce
server:
  port: 8234
#  ?????????????API??????/api????????????
  servlet:
    context-path: /api

# Springdoc-openapi
#???????????API?????"default"??????????
springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: com.wuyinai.wuaipdce.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn